# Generated by Django 3.1.2 on 2020-10-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('imgurl', models.ImageField(blank=True, null=True, upload_to='Images/')),
                ('smallimgurl', models.ImageField(blank=True, null=True, upload_to='Images/')),
                ('numpages', models.IntegerField()),
                ('formatbook', models.TextField(blank=True, null=True)),
                ('publisher', models.TextField(blank=True, null=True)),
                ('avgrating', models.IntegerField()),
                ('ratecount', models.IntegerField()),
                ('author', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
