# Generated by Django 3.1.2 on 2020-12-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
