# Generated by Django 3.1.2 on 2020-10-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='imgurl',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='smallimgurl',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='Images/'),
        ),
    ]
