# Generated by Django 3.1.2 on 2020-10-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyma', '0002_auto_20201030_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='avgrating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='numpages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='ratecount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
