# Generated by Django 3.1.2 on 2020-11-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyma', '0003_auto_20201030_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='formatbook',
        ),
    ]
