# Generated by Django 3.1.2 on 2020-11-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyma', '0004_remove_book_formatbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='imgurl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='smallimgurl',
            field=models.TextField(blank=True, null=True),
        ),
    ]
