# Generated by Django 3.1.2 on 2020-11-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyma', '0001_initial'),
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='mybook',
            field=models.ManyToManyField(to='kyma.book'),
        ),
    ]
