# Generated by Django 3.1.2 on 2020-12-06 14:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kyma', '0001_initial'),
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userrate', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('current_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyma.book')),
            ],
        ),
    ]
