# Generated by Django 3.1.2 on 2020-12-16 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myquote',
            name='account',
        ),
        migrations.RemoveField(
            model_name='myquote',
            name='current_book',
        ),
        migrations.RemoveField(
            model_name='ratinguser',
            name='account',
        ),
        migrations.RemoveField(
            model_name='ratinguser',
            name='current_book',
        ),
        migrations.DeleteModel(
            name='LikeQuote',
        ),
        migrations.DeleteModel(
            name='MyQuote',
        ),
        migrations.DeleteModel(
            name='Ratinguser',
        ),
    ]
