# Generated by Django 3.1.2 on 2020-11-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_mybook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybook',
            name='state',
            field=models.CharField(max_length=10),
        ),
    ]
