# Generated by Django 3.1.2 on 2020-11-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_account_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_photo',
            field=models.ImageField(default='default.png', upload_to='profile_photos'),
        ),
    ]
