# Generated by Django 3.1.2 on 2020-12-06 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyma', '0001_initial'),
        ('quickstart', '0002_myrate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyRate',
            new_name='Ratinguser',
        ),
    ]
