# Generated by Django 3.1.2 on 2020-12-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_likequote'),
    ]

    operations = [
        migrations.AddField(
            model_name='myquote',
            name='Likes',
            field=models.IntegerField(default=0),
        ),
    ]
