# Generated by Django 3.1.2 on 2020-12-27 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
