# Generated by Django 3.1.2 on 2020-12-29 17:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_group_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='send_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
