# Generated by Django 3.1.2 on 2020-12-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_chat_send_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
