# Generated by Django 3.1.2 on 2020-12-11 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_auto_20201210_1829'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DisLikeQuote',
        ),
    ]
