# Generated by Django 3.1.2 on 2020-12-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_delete_dislikequote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myquote',
            name='Dislike',
        ),
        migrations.AlterField(
            model_name='myquote',
            name='Likes',
            field=models.IntegerField(default=0),
        ),
    ]
