# Generated by Django 3.1.2 on 2021-01-28 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_num', models.IntegerField(default=1)),
                ('question_text', models.TextField()),
                ('a_text', models.TextField()),
                ('b_text', models.TextField()),
                ('c_text', models.TextField()),
                ('d_text', models.TextField()),
                ('key', models.CharField(max_length=1)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.quiz')),
            ],
        ),
    ]
