# Generated by Django 3.1.2 on 2021-01-29 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0009_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question_count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
        ),
    ]
